version: '3.8'
services:

  envoy:
    image: "envoyproxy/envoy-alpine:v1.17-latest"
    container_name: cad_envoy_gateway
    restart: always
    volumes:
      - ./cad_envoy/envoy-config/:/etc/envoy/:rw
      - '/etc/localtime:/etc/localtime:ro'
    network_mode: host
    environment:
      - "ENVOY_UID=0"
      - "TZ=Hongkong"

  envoy_9444:
    image: "envoyproxy/envoy-alpine:v1.17-latest"
    container_name: cad_envoy_9444
    restart: always
    ports:
      - "9904:9902"
      - "9444:9443"
    volumes:
      - ./cad_envoy/envoy_config_9444/:/etc/envoy/:rw
      - '/etc/localtime:/etc/localtime:ro'
    #network_mode: host
    networks:
      - envoy_9444
    environment:
      - "ENVOY_UID=0"
      - "TZ=Hongkong"

  rct_envoy:
    image: "envoyproxy/envoy-alpine:v1.17-latest"
    container_name: rct_envoy_gateway
    restart: always
    ports:
      - "9905:9902"
      - "9445:9443"
    networks:
      - envoy_9444
    volumes:
      - ./rct_envoy/envoy-config/:/etc/envoy/:rw
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - "ENVOY_UID=0"
      - "TZ=Hongkong"

  pd_envoy:
    image: "envoyproxy/envoy-alpine:v1.17-latest"
    container_name: pd_envoy_gateway
    restart: always
    ports:
      - "9906:9902"
      - "9446:9443"
    networks:
      - envoy_9444
    volumes:
      - ./cad_pd_envoy/envoy-config/:/etc/envoy/:rw
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - "ENVOY_UID=0"
      - "TZ=Hongkong"

  dte_envoy:
    image: "envoyproxy/envoy-alpine:v1.17-latest"
    container_name: dte_envoy_gateway
    restart: always
    ports:
      - "9907:9903"
      - "9447:9443"
    networks:
      - envoy_9444
    volumes:
      - ./dte_envoy/envoy-config/:/etc/envoy/:rw
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      - "ENVOY_UID=0"
      - "TZ=Hongkong"

  # 如果需要缓存服务，请确保它以主机模式运行
  # cache_server:
  #   build: cache_server/
  #   container_name: cache_server
  #   restart: always
  #   # ports:
  #   #  - "47500:47500"
  #   network_mode: host

  # Action 不需要缓存，默认使用网桥模式运行
  cad_action:
    build: cad_action/
    container_name: cad_action
    restart: always
    # ports:
    #  - "8014:8013"
    #  - "8181:8080"
    volumes:
      - ./cad_action/logs:/app/logs:rw
      - ./cad_action/appsettings.json:/app/appsettings.json:rw
      - ./cad_action/cacheSettings.json:/app/cacheSettings.json:rw
      - '/etc/localtime:/etc/localtime:ro'
    network_mode: host
    # networks:
    #   - devops_network
    environment:
      - "TZ=Hongkong"
      - "ASPNETCORE_ENVIRONMENT=Development"
      # Action_Assign 不需要缓存，默认使用网桥模式运行，此服务不需要由Envoy进行代理
      #cad_action_assign:
      #build: cad_action_assign/
      #container_name: cad_action_assign
      #restart: always
      # ports:
      #  - "8015:80"
      #network_mode: host
      # networks:
      #  - devops_network
      #volumes:
      #- ./cad_action_assign/logs:/app/logs:rw
      #- ./cad_action_assign/appsettings.json:/app/appsettings.json:rw
      #- ./cad_action_assign/cacheSettings.json:/app/cacheSettings.json:rw
      #environment:
      #- "TZ=Hongkong"
      #- "ASPNETCORE_ENVIRONMENT=Development"

      # Dispatch依赖缓存，必须使用主机模式运行
  cad_dispatch:
    build: cad_dispatch/
    container_name: cad_dispatch
    restart: always
    volumes:
      - ./cad_dispatch/logs:/app/logs:rw
      - ./cad_dispatch/appsettings.json:/app/appsettings.json:rw
      - ./cad_dispatch/cacheSettings.json:/app/cacheSettings.json:rw
      - ./cad_dispatch/tactilonSettings.json:/app/tactilonSettings.json:rw
      - ./cad_dispatch/nlog.config:/app/nlog.config:rw
      - '/etc/localtime:/etc/localtime:ro'
    network_mode: host
    environment:
      - "TZ=Hongkong"

  # Incident依赖缓存，必须使用主机模式运行
  cad_incident:
    build: cad_incident/
    container_name: cad_incident
    restart: always
    volumes:
      - ./cad_incident/appsettings.json:/app/appsettings.json:rw
      - ./cad_incident/cacheSettings.json:/app/cacheSettings.json:rw
      - ./cad_incident/nlog.config:/app/nlog.config:rw
      - ./cad_incident/logs:/app/logs:rw
      - '/etc/localtime:/etc/localtime:ro'
    network_mode: host
    environment:
      - "TZ=Hongkong"

  # Message依赖缓存，必须使用主机模式运行
  cad_message:
    build: cad_message/
    container_name: cad_message
    restart: always
    # ports:
    #  - "8106:8105"
    #  - "8101:8082"
    volumes:
      - ./cad_message/logs:/app/logs:rw
      - ./cad_message/appsettings.json:/app/appsettings.json:rw
      - ./cad_message/cacheSettings.json:/app/cacheSettings.json:rw
      - '/etc/localtime:/etc/localtime:ro'
    network_mode: host
    # networks:
    #   - devops_network
    environment:
      - "TZ=Hongkong"
      - "ASPNETCORE_ENVIRONMENT=Development"

  # ResStatus不依赖缓存，默认以网桥模式运行，此服务不需要由Envoy进行代理。
  # 如需代理，请在Envoy中使用cad_resstatus代替具体的IP地址，并配置路由、cluster、JSON转码。
  cad_resstatus:
    build: cad_resstatus/
    container_name: cad_resstatus
    restart: always
    environment:
      - "TZ=Hongkong"
    # ports:
    #  - "9015:9005"
    network_mode: host
    # networks:
    #   - devops_network
    volumes:
      - ./cad_resstatus/logs:/app/logs:rw
      - ./cad_resstatus/appsettings.json:/app/appsettings.json:rw
      - ./cad_resstatus/cacheSettings.json:/app/cacheSettings.json:rw
      - /etc/localtime:/etc/localtime:ro

  # Session不依赖缓存，默认以网桥模式运行，此服务需要由Envoy进行代理。
  # 请在Envoy中使用session_grpc代替具体的IP地址，并配置路由、cluster、JSON转码。
  session_grpc:
    build: session_grpc/
    container_name: session_grpc
    restart: always
    # ports:
    #  - "9051:9050"
    #  - "8003:8002" 
    network_mode: host
    # networks:
    #   - devops_network
    volumes:
      - ./session_grpc/logs:/app/logs:rw
      - ./session_grpc/appsettings.json:/app/appsettings.json:rw
      - '/etc/localtime:/etc/localtime:ro'

  # Protocolmapping不依赖缓存，默认以网桥模式运行，此服务需要由Envoy进行代理。
  # 请在Envoy中使用gis_protocolmapping代替具体的IP地址，并配置路由、cluster、JSON转码。
  gis_protocolmapping:
    build: gis_protocolmapping/
    container_name: gis_protocolmapping
    restart: always
    environment:
      - "TZ=Hongkong"
    network_mode: host
    volumes:
      - ./gis_protocolmapping/logs:/app/logs:rw
      - ./gis_protocolmapping/appsettings.json:/app/appsettings.json:rw
      - '/etc/localtime:/etc/localtime:ro'

  # PhoneBook不依赖缓存，默认以网桥模式运行，此服务不需要由Envoy进行代理。
  # 如需代理，请在Envoy中使用cad_resstatus代替具体的IP地址，并配置路由、cluster、JSON转码。
  cad_phonebook:
    build: cad_phonebook/
    container_name: cad_phonebook
    restart: always
    environment:
      - "TZ=Hongkong"
    #ports:
    #  - "44364:44364"
    network_mode: host
    # networks:
    #   - devops_network
    volumes:
      - ./cad_phonebook/logs:/app/logs:rw
      - ./cad_phonebook/appsettings.json:/app/appsettings.json:rw
      - '/etc/localtime:/etc/localtime:ro'

  # CEB依赖缓存，必须使用主机模式运行
  cad_ceb:
    build: cad_ceb/
    container_name: cad_ceb
    restart: always
    # ports:
    #  - "44322:44322"
    volumes:
      - ./cad_ceb/logs:/app/logs:rw
      - ./cad_ceb/appsettings.json:/app/appsettings.json:rw
      - ./cad_ceb/cacheSettings.json:/app/cacheSettings.json:rw
      - '/etc/localtime:/etc/localtime:ro'
    network_mode: host
    # networks:
    #   - devops_network
    environment:
      - "TZ=Hongkong"
      - "ASPNETCORE_ENVIRONMENT=Development"

  # ComplaintEnquiry依赖缓存，必须使用主机模式运行
  cad_complaintenquiry:
    build: cad_complaintenquiry/
    container_name: cad_complaintenquiry
    restart: always
    volumes:
      - ./cad_complaintenquiry/logs:/app/logs:rw
      - ./cad_complaintenquiry/appsettings.json:/app/appsettings.json:rw
      - ./cad_complaintenquiry/cacheSettings.json:/app/cacheSettings.json:rw
      - ./cad_complaintenquiry/nlog.config:/app/nlog.config:rw
      - '/etc/localtime:/etc/localtime:ro'
    network_mode: host
    environment:
      - "TZ=Hongkong"

  # HKPF InterfaceService必须使用主机模式运行
  cad_hkpf:
    build: cad_hkpf/
    container_name: cad_hkpf
    restart: always
    #ports:
      #- "8206:80"
    #networks:
      #- envoy_9444
    volumes:
      - ./cad_hkpf/logs:/app/logs:rw
      - ./cad_hkpf/appsettings.json:/app/appsettings.json:rw
      - '/etc/localtime:/etc/localtime:ro'
    network_mode: host
    environment:
      - "TZ=Hongkong"
    extra_hosts:
      - "fgms-idsrv.fgms.dev.com:192.168.6.33"


  dte:
    build: dte/
    container_name: dte
    restart: always
    volumes:
      - ./dte/appsettings.json:/app/appsettings.json:rw
      - ./dte/connectionConfigs.json:/app/connectionConfigs.json:rw
      - ./dte/nlog.config:/app/nlog.config:rw
      - ./dte/logs:/app/logs:rw
      - '/etc/localtime:/etc/localtime:ro'
    network_mode: host
    environment:
      - "TZ=Hongkong"


# networks:
#   devops_network:
#     driver: host
networks:
  default:
    external:
      name: host
  envoy_9444:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.176.0/20
