version: '3.7'
services:

  dm_log:
    build: dm_log/
    container_name: dm_log
    restart: always
    volumes:
      - ./dm_log/appsettings.json:/app/appsettings.json:rw
      - ./dm_log/nlog.config:/app/nlog.config:rw
      - ./dm_log/logs:/app/logs:rw
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - 8001:80
    environment:
      - "TZ=Asia/Shanghai"



